#!/bin/bash
#DAEMON='/usr/local/bin/arduino_controler.py'

#Uncomment to change Listening interface. Default localhost
#BIND_ADDRESS=localhost
#Uncomment to change Listening port (TCP). Default is 9999
#TCP_PORT=9999
#Uncomment to change maximum number of waiting connections (TCP). Default is 5
#QUEUE_SIZE=5

#Uncomment to change serial port to connect the arduino. Default is /dev/ttyACM0
#DEVICE=/dev/ttyACM0
#Uncomment to change serial port baud rate. Default is 9600
#BAUD_RATE=9600


#Uncomment to swith in verbose mode
# note: if a logs.conf file exists in /etc/arduino_controler, this paramter is
#       overloded by the configuration in logs.conf
#VERBOSE=yes
