#!/bin/bash

#--------------------------------------------------------
 # Module Name : examples
 # Version : 1.0.0
 #
 # Software Name : SerialCom
 # Version : 1.0
 #
 # Copyright (c) 2015 Zorglub42
 # This software is distributed under the Apache 2 license
 # <http://www.apache.org/licenses/LICENSE-2.0.html>
 #
 #--------------------------------------------------------
 # File Name   : simpleTest
 #
 # Created     : 2015-12
 # Authors     : Zorglub42 <contact(at)zorglub42.fr>
 #
 # Description :
 #     Shell example to connect socket server
 #--------------------------------------------------------
 # History     :
 # 1.0.0 - 2015-12-03 : Release of the file
 #
 

SERVER=localhost
PORT=9999


function sendCommand() {
	echo $1 | nc $SERVER $PORT
}


for v in `sendCommand V`; do
	echo "Value=$v"
done
